dataset_path: few_data/
train_dataset: tieredimagenet
train_dataset_args: {split: train, augment: aug, batch_size: 128}
# val_dataset: tieredimagenet
# val_dataset_args: {split: train_phase_val, batch_size: 128}
fs_dataset: tieredimagenet
fs_dataset_args: {split: test}
eval_fs_epoch: 5
ep_per_batch: 4
model: classifier
model_args:
    encoder: resnet12 #resnet18
    encoder_args: {}
    classifier: nn-classifier 
    # classifier: linear-classifier 
    classifier_args: {n_classes: 351}

max_epoch: 100
optimizer: sgd
optimizer_args: {lr: 0.1, weight_decay: 5.e-4, milestones: [90]}  # learning rate decays at epoch 90

save_epoch: 5
visualize_datasets: False #True
