dataset_path: few_data/
train_dataset: miniimagenet
train_dataset_args: {split: train, augment: aug_co, batch_size: 4}  


model: meta-co
model_args: 
    encoder: resnet12
    encoder_args: {}
    
load_encoder: ./save/classifier_miniimagenet_resnet12/epoch-last.pth

n_way: 5
n_shot: 1
n_query: 15
train_batches: 100

max_epoch: 20
optimizer: sgd
optimizer_args: {lr: 0.001, weight_decay: 5.e-4}

visualize_datasets: False #True
