dataset_path: few_data/
train_dataset: cub
train_dataset_args: {split: train}
val_dataset: cub
val_dataset_args: {split: test}
test_dataset: cub
test_dataset_args: {split: val}

model: meta-baseline
model_args: 
    encoder: resnet12 
    encoder_args: {}

load_encoder: ./save/classifier_cub_resnet12-nn-classifier/epoch-last.pth
# load_encoder: ./save/classifier_cub_resnet18-nn-classifier/epoch-last.pth
# load_encoder: ./save/classifier_cub_resnet12/epoch-last.pth
# load_encoder: ./save/classifier_cub_resnet18/epoch-last.pth

n_way: 5
n_shot: 1 #5
n_query: 15
train_batches: 200
ep_per_batch: 4

max_epoch: 20
optimizer: sgd
optimizer_args: {lr: 0.001, weight_decay: 5.e-4}

visualize_datasets: True
